### PR TITLE
Configuration refactoring and necessary changes for APEL

### PR DESCRIPTION
**Pull request by valtri**
# Summary

Finalize APEL accounting and make some changes in helm configuration:

* both accounting transfers are disabled by default (EOSC, APEL)
* more config parameters to helm (Prometheus credentials and filter, k8s storage, APEL spool and broker, ...)
* simplify configuration for APEL (apelSpool directory not neeed to set)
* fix client certificates setup for APEL (copied from the mounted location)
* update README

---

**Related issue :**

### CODE REVIEW

**Comment by andrea-manzi** [comment]
shall we mark it as ready for review?

**Comment by valtri** [comment]
Yes, I think the changes are ready. The APEL transfer has never been used yet, but everything looks OK.

**Review by andrea-manzi — APPROVED** [review]
looks fine! let's wait for successfull tests and we can merge

**Review by enolfc — APPROVED** [review]
LGTM

**Pull request merged**
